### ISSUE TITLE
How to setup your PMS for a hostel

### ISSUE THREAD

**Issue by Stephanisk** [OCA/pms#195]
Hello,

We are running a hostel and i am wondering how to setup your system for a hostel, meaning in a room there are multiple beds and each bed can be assigned to a different customer. In a normal setup as i have now, when the room is booked, i can not asign another reservation to the same room, although there are still beds free in that room.

Any help would be very greatly appreciated.

Regards

**Comment by DarioLodeiros** [comment]
Hi Stephan,

Sorry by delayed in the response.
If you want to sell independent beds you must create a "room" of type "bed" for each bed you have. Normally we create a room type for the entire room (eh. 100-8b), of the type beds, and then 8 rooms of that type (the beds)
