### ISSUE TITLE
Doc link for pms is broken

### ISSUE THREAD

**Issue by vdewulf** [OCA/pms#211]
## Module
pms

## Describe the bug
I clicked on the link in the readme section with the documentation link
https://github.com/OCA/pms/blob/14.0/pms/roomdoo.com
and it shows a 404 not found page

## To Reproduce
Click there: https://github.com/OCA/pms/blob/14.0/pms/roomdoo.com

**Expected behavior**
Manual is displayed :)
The module seems very complete, I'd like to learn how to use it!
Thanks a lot

**Comment by max3903** [comment]
We made and used the modules in this branch:
https://github.com/OCA/pms/tree/14.0-pms_base

for Casai:
https://www.opensourceintegrators.com/publications/casai-Odoo-support-growth

**Comment by francesco-ooops** [comment]
Hi, not sure that link was ever correct, I would contact https://www.roomdoo.com/contacto/ for info anyway :)

**Comment by DarioLodeiros** [comment]
Hi Francesco,

We use the pms in production, but it is in alpha version so we are still
consolidating all the flows and with constant changes in the module. We'll
probably start working on stabilizing it after the summer in a v16.

**Comment by vdewulf** [comment]
Thanks all for your replies!
