### ISSUE TITLE
planning

### ISSUE THREAD

**Issue by Johnrivera7** [OCA/pms#235]
Is there the possibility of showing a schedule / planing of rooms and occupations? something similar to that of vertical hotel?

**Comment by DarioLodeiros** [comment]
Update the module, you have a new planning view on reservations menu

**Comment by Johnrivera7** [comment]
Hello @DarioLodeiros , thank you very much for the help, I have modified the code in several parts, could you tell me which code sheets should I merge or which is the branch please?

**Comment by Johnrivera7** [comment]
ready, I found it, many thanks
