### ISSUE TITLE
Error installing PMS module | AttributeError: 'Many2one' object has no attribute 'check_pms_properties'

### ISSUE THREAD

**Issue by herawais** [OCA/pms#39]
File /pms/multi_pms_properties/models.py", line 32, in write
    or (field.relational and field.check_pms_properties)
Exception

 raise exception.with_traceback(None) from new_cause
AttributeError: 'Many2one' object has no attribute 'check_pms_properties'

**Comment by tate11** [comment]
https://github.com/OCA/pms/issues/19#issuecomment-860540057
