### ISSUE TITLE
AttributeError: 'Many2one' object has no attribute 'check_pms_properties'

### ISSUE THREAD

**Issue by gobezu** [OCA/pms#43]
Upon installation I get the following error details of which is attached and the installation halts:

`  File "/opt/odoo14/oca/pms/multi_pms_properties/models.py", line 32, in write
    or (field.relational and field.check_pms_properties)
AttributeError: 'Many2one' object has no attribute 'check_pms_properties'`

[error.txt](https://github.com/OCA/pms/files/6826456/error.txt)

**Comment by DarioLodeiros** [comment]
https://github.com/OCA/pms/issues/19
