### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by max3903** [OCA/pms#81]
**Is your feature request related to a problem?**

`pms` seems to be covering a pretty large scope which makes the module more complicated to evaluate, learn, select, maintain and migrate.

**Describe the solution you'd like**

I would like to explore/propose splitting the module:

* pms (or pms_base to avoid conflicts) with various settings
* pms_account
* pms_account_asset
* pms_sale
* pms_stock

**Describe alternatives you've considered**

* Starting from scratch
* Serpent CS PMS: https://serpentcs.in/product/property-management-system

**Additional context**

My customer is renting properties to owners, furnishing them (furniture value depreciates over time so the requirement for `pms_account_asset`) and selling reservations on various websites.

**Comment by eantones** [comment]
Hello @max3903 , thank you for your comments. At this moment, the OCA PMS is focused on Hotel Management and, according to your comments and the mention of the Serpent solution, it seems you are referring to something more generic, something more Real Estate oriented such as property master and creation, property tenancy, maintenance process, commission calculation, recurring expenses, etc.. Definitely this is something we may consider in the future and any contribution on that aspect will be welcome.

Regarding the main PMS module, we totally agree with you, it's growing too much and we're gonna need to split it into several modules sooner than later. We thought about doing it taking advantage of the v15 migration but we might evaluate do do it in this very v14 as well. Lastly I'd like to let you know there's another module, it's a module based on the OCA Connector and it's used to connect to a Wubook channel manager. It's still in a PR but it's stable and already in production, we are finishing the final refactor before pushing it to the main branch.

Please let me know if you need any further information.

Thanks :-)

**Comment by max3903** [comment]
Thanks for your answer @eantones.

Since you mentioned integration, I saw in some screenshots some Booking.com and Airbnb stuff. Are you integrated with Guesty (https://guesty.com)?

**Comment by max3903** [comment]
@eantones Here is a 1st version of the plan to refactor:

# pms_base (in #84)

- [x] Base module that provide the “Properties” apps with menu, settings, groups and data
- [x] Module will provide the Property object with the address, a parent, an owner and the physical characteristics: dimensions, list of rooms.
- [ ] Module will provide a wizard to mass-create children of a property

## Menu

* Dashboard
* Operations
* Master Data
  * Properties
  * Owners
* Reporting
* Configuration
  * Settings
    * Unit of Measures
      * Area: Square Meter or Square Foot
    * Accounting
      * Manage profitability
      * Manage depreciation and amortizations
      * Manage utility contracts and others recurring invoices/bills
    * Sell reservations
      * Sell online
    * Publish your properties
    * Integrations
      * Guesty
      * Wubook
  * Properties
    * Property Types: Appartment, House, etc.
    * Room Types: Bedroom, Living Room, Kitchen

## Groups

- [x] PMS User
- [x] PMS Manager

Technical groups

- [x] Show amenities
- [x] Show rooms

# pms_account (in #87)

- [x] Module will allow to link a property to customer invoices and vendor bills
- [x] Module will also allow to link the property to an analytic account

# pms_account_asset (in #88)

- [x] Module will allow to link a property to many assets

# pms_contract (in #89)

- [x] Module will allow to link a property to many contracts and manage utilities
- [x] Add a Contracts menuitem in Operations

# pms_sale

- [x] Module will depend on pms_base and sale to allow the user to sell/rent properties and reservations
- [x] Module will depend on web_timeline to provide a timeline view with filters on the search panel and manage reservations
- [x] Module will allow to configure "Reservation" products (similar to “Event Ticket”)
- [x] Module will provide the status of the property and the reservation
- [x] Add a menu “Reservations” in Dashboard, Operations
- [x] pms.reservation with start date, end date, checkin, checkout, list of guests, sale order, customer, property, state (new, confirmed, waiting payment, paid) + chatter
- [x] Views: Timeline, Tree, Form, Calendar

# pms_crm

- [x] Add a “Property” field on the crm.lead
- [x] Add a “X Lead(s)” smart button on the property

# pms_website

- [x] Module will depend on pms_base and website
- [x] Module will allow the user to expose the properties on the website with 1 page per properties
- [x] Module will provide the tools to organize properties with categories, search bar and filters
- [x] Add a button “Published” on the property (similar to product in website_sale)

# pms_website_sale

- [x] Module will depend on pms_website, pms_sale and website_sale
- [x] Module allow to buy or rent the property and book reservations
- [x] Add the reservation information on the property and link/button to add/proceed to the cart

**Comment by DarioLodeiros** [comment]
Hi Max! Thanks for your interest and your participation. I wanted to comment on several points:
- I don't know if you would have a problem if we could propose this refactoring for v15. The pms is in alpha state and we are still validating it while we are implementing it in 50 hotel establishments. If we take advantage of the refactoring in a v15 branch instead of v14 we can work on a significant improvement like the one you propose and develop the migration scripts.
- If we could propose the refactoring for v15, it would add improvements in certain architecture and naming issues to make the module more comprehensive and generic (e.g., room -> accommodation, reservations by hours, etc ...)
- guesty.com is a PMS with the focus on tourist apartments, it practically has a 100% overlap in functionalities with OCA / pms, integration is possible, but I wanted to clarify this point. Currently we have the system integrated with wubook, which is a channel manager that allows us to connect with dozens of online sales channels (booking, expedia, airbnb ...), the integration has a base module (pms_connector: https: // github. com / commitsun / pms / tree / 14.0-connector_pms / connector_pms) and another one that is specific to wubook. I think the connector_pms module would be suitable for guesty as well.

Tell me if you think it is ok to propose this refactoring for v15, and we will see how to carry it out.
Thanks!

**Comment by max3903** [comment]
@DarioLodeiros My project is on version 14 and I need to deliver by the end of the year.

**Comment by carlosrve** [comment]
Hi @max3903 ! We will be implementing PMS in a project, we are deciding right now if we migrate the code to v15 or if we stick with v14. What are your plans with this refactor?

Our timeframe will not allow us to wait or absorbe the refactor on v15 before going into production, but we could participate in the refactor if we introduce it after migrating the existing code to v15 and then proposing a PR with the respective migration scripts. In that way we could migrate the code to v15 in the next days and propose the PR.

cc @hugho-ad @julioserna

**Comment by DarioLodeiros** [comment]
Hello good!
We are currently implementing and developing the solution in a hotel chain with more than 60 establishments, that is why we were not yet able to participate in the refactoring. But if it's okay with you, I think it's good to do a video call session to coordinate that refactoring work, at least I could tell you about known problems and the roadmap that we have. I remain at your disposal.

**Comment by carlosrve** [comment]
Thanks @DarioLodeiros ! OK yes. Let's wait for @max3903 response to coordinate the next step.

For us it is feasible to work after December, for the same reason, we have to deploy this into production, in v15 in the next month, but we will not be stopping there. So we could redirect some of the project resources to the refactor and cleanup of this app.

**Comment by pka2why** [comment]
Hello @DarioLodeiros 
I am looking for a solution for small hotel to work with odoo and some booking services.  I see you mention there is a working solution using Wubook.  
Is that a solution we can use over here in Dominican Republic ?
i am really interested in this solution, please if you or anyone here could give a bit more of information regarding this idea i will really appreciate the help.
Sorry if i using this tool wrong.

Thanks

**Comment by max3903** [comment]
@carlosrve @DarioLodeiros My customer is live and the modules based on `pms_base` starts to be pretty stable now. I also have more availability to discuss. When would be a good time for you to have a call? I am in Mexico General timezone.

**Comment by DarioLodeiros** [comment]
Sorry I missed reading these messages. Glad to be able to have that contact to review the repository plan.
@max3903  , if you can schedule a day from March 7 you can count on me, I'll send you my email dario@roomdoo.com in case you create the event for the invitation. I am in Spain, so I understand that to fit in well it must be in the morning in Mexico and in the afternoon in Spain, right?
@carlosrve , do you join the session?

**Comment by max3903** [comment]
@DarioLodeiros Sorry for the late answer. I sent you an invitation for Wednesday if you still want to discuss.
